"""Initial migration

Revision ID: 3d46724931c7
Revises: 
Create Date: 2016-07-28 17:04:34.508955

"""

# revision identifiers, used by Alembic.
revision = '3d46724931c7'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('colour', sa.Unicode(length=6), server_default='CCCCCC', nullable=False),
    sa.Column('content', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('note_id', name=op.f('notes_pkey')),
    schema='zingk'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes', schema='zingk')
    ### end Alembic commands ###
